[workflow]
h1-channel-name = H1:FAKE_DATA
l1-channel-name = L1:FAKE_DATA
v1-channel-name = V1:FAKE_DATA
k1-channel-name = K1:FAKE_DATA

[workflow-datafind]
datafind-method = AT_RUNTIME_FAKE_DATA
datafind-check-segment-gaps = no_test
datafind-check-frames-exist = no_test
datafind-check-segment-summary = no_test
datafind-h1-frame-type = H1_HOFT_C00
datafind-l1-frame-type = L1_HOFT_C00
datafind-v1-frame-type = V1_HOFT_C00
datafind-k1-frame-type = K1_HOFT_C00

[workflow-segments]
segments-method = ALL_SINGLE_IFO_TIME
segments-vetoes = +CAT_2,+CAT_H
; segments-database-url = https://segments.ligo.org
;segments-veto-definer-url = https://git.ligo.org/detchar/veto-definitions/raw/edf19cf3bed4a65708d553bdb822bd08491b8a19/cbc/O2/H1L1V1-CBC_VETO_DEFINER_C02_O2_1164556817-23176801.xml
segments-veto-definer-url = /home/rahul.dhurkunde/searches/ML-pycbc/4-det/VDF.xml 
;segments-dq = +IDQ-OVL_LOGLIKE_GT_5_PAD_250MS

[workflow-segments-h1]
segments-science = +DMT-ANALYSIS_READY:1,-CAT_1
;segments-source = dqsegdb
;segments-database-url = https://segments.ligo.org

[workflow-segments-l1]
segments-science = +DMT-ANALYSIS_READY:1,-CAT_1
;segments-source = dqsegdb
;segments-database-url = https://segments.ligo.org

[workflow-segments-v1]
segments-science = +ITF_SCIENCE:1,-CAT_1
;segments-source = dqsegdb
;segments-database-url = https://segments.ligo.org

[workflow-segments-k1]
segments-science = +GRD_SCIENCE_MODE:1,-CAT_1
;segments-science-file = /home/rahul.dhurkunde/searches/ML-pycbc/4-det/k1_science.xml
;segments-vetoes-file = /home/rahul.dhurkunde/searches/ML-pycbc/4-det/k1_vetoes.xml

;[workflow-segments-dq]
;segments-source = file
;
;[workflow-data_quality-h1_idq]
;dq-ifo = H1
;dq-type = flag
;dq-name = H1:IDQ-OVL_LOGLIKE_GT_5_PAD_250MS
;
;[workflow-data_quality-l1_idq]
;dq-ifo = L1
;dq-type = flag
;dq-name = L1:IDQ-OVL_LOGLIKE_GT_5_PAD_250MS
;
;[workflow-data_quality-v1_idq]
;dq-ifo = V1
;dq-type = flag
;dq-name = V1:IDQ-OVL_LOGLIKE_GT_5_PAD_250MS
;
;[workflow-data_quality-k1_idq]
;dq-ifo = V1
;dq-type = flag
;dq-name = V1:IDQ-OVL_LOGLIKE_GT_5_PAD_250MS
