; Configuration file for running a workflow with inspiral jobs on the OSG
;
; Inspiral jobs are run via OSG, the inspiral executable is supplied from a singularity container

[executables]
inspiral = singularity:///usr/local/bin/pycbc_inspiral

; Set the inspiral jobs' site to the OSG
[pegasus_profile-inspiral]
pycbc|site = osg

[datafind]
urltype = osdf

