# This config file defines the access point (AP) tokens used to verify credentials by Condor.
## On CIT submit nodes, token information is initialized at the beginning of an SSH session.

; This is the lines we need for scitokens
[pegasus_profile-condorpool_shared&pegasus_profile-condorpool_symlink&pegasus_profile-osg]
condor|use_oauth_services = scitokens

; This line is needed to find the credential on condor
env|BEARER_TOKEN_FILE = $$(CondorScratchDir)/.condor_creds/scitokens.use
