; Chunk-specific information for chunk 18 of O4

[workflow]
#UTC 2023-06-01T01:46:25
start-time = 1438218818
end-time =   1439318818

[results_page]
analysis-title = "PyCBC offline search"
analysis-subtitle = "O4 broad analysis chunk 18"

[workflow-segments-dq]
segments-dq-file = /home/rahul.dhurkunde/searches/ML-pycbc/4-det/DQ-dummy-file.xml 
