[workflow]
h1-channel-name = H1:GDS-FAKE_STRAIN
l1-channel-name = L1:GDS-FAKE_STRAIN
v1-channel-name = V1:GDS-FAKE_STRAIN
k1-channel-name = K1:GDS-FAKE_STRAIN

[workflow-datafind]
datafind-method = AT_RUNTIME_SINGLE_FRAMES
datafind-check-segment-summary = no_test
datafind-h1-frame-type = H1_HOFT_C00_AR
datafind-l1-frame-type = L1_HOFT_C00_AR
datafind-v1-frame-type = HoftAR1
datafind-k1-frame-type = HoftAR1

[workflow-segments]
segments-veto-definer-url = /home/rahul.dhurkunde/searches/ML-pycbc/4-det/VDF.xml 
segments-dq = +IDQ-OVL_LOGLIKE_GT_5_PAD_250MS

[workflow-segments-h1]
segments-science = +DMT-ANALYSIS_READY,-CAT_1
segments-vetoes = +CAT_2,+CAT_H
segments-source = dqsegdb
segments-database-url = https://segments.ligo.org

[workflow-segments-l1]
segments-science = +DMT-ANALYSIS_READY,-CAT_1
segments-vetoes = +CAT_2,+CAT_H
segments-source = dqsegdb
segments-database-url = https://segments.ligo.org

[workflow-segments-v1]
segments-science = +ITF_SCIENCE_OFFLINE_O4:1,-CAT_1
segments-vetoes = +CAT_2,+CAT_H
segments-source = dqsegdb
segments-database-url = https://segments.ligo.org

[workflow-segments-k1]
segments-science = +ITF_SCIENCE_OFFLINE_O4:1,-CAT_1
segments-vetoes = +CAT_2,+CAT_H
segments-source = gwosc
segments-science-file = /home/rahul.dhurkunde/searches/ML-pycbc/4-det/k1_science.xml
segments-vetoes-file = /home/rahul.dhurkunde/searches/ML-pycbc/4-det/k1_vetoes.xml

;[workflow-segments-dq]
;segments-source = file
;
;[workflow-data_quality-h1_idq]
;dq-ifo = H1
;dq-type = flag
;dq-name = H1:IDQ-OVL_LOGLIKE_GT_5_PAD_250MS
;
;[workflow-data_quality-l1_idq]
;dq-ifo = L1
;dq-type = flag
;dq-name = L1:IDQ-OVL_LOGLIKE_GT_5_PAD_250MS
;
;[workflow-data_quality-v1_idq]
;dq-ifo = V1
;dq-type = flag
;dq-name = V1:IDQ-OVL_LOGLIKE_GT_5_PAD_250MS
;
;[workflow-data_quality-k1_idq]
;dq-ifo = V1
;dq-type = flag
;dq-name = V1:IDQ-OVL_LOGLIKE_GT_5_PAD_250MS
