[workflow-ifos]
h1 = 
l1 =
v1 =

[coinc-h1v1&coinc-l1v1]
;The corrections are tuned w.r.t h1l1 on O4b injections. Reference_ifos is required in case an IFO is missing.
statistic-keywords = statistic_correction:-0.4 reference_ifos:H1

[coinc-h1l1v1]
;The corrections are tuned w.r.t h1l1 on O4b injections. Reference_ifos is required in case an IFO is missing.
statistic-keywords = statistic_correction:2.9 reference_ifos:H1

; successive levels of decimation to reduce memory load for background coincs below stated values
[coinc-full_data-h1l1]
; H1L1 unaffected by stat corrections
loudest-keep-values = [15:5,10:30,5:30,0:30]

[coinc-full_data-h1v1&coinc-full_data-l1v1]
; negative statistic correction / lower stat than H1L1
loudest-keep-values = [11:5,6:30,1:30,-4:30]

[coinc-full_data-3det]
; positive statistic correction but triple background is well below H1L1
loudest-keep-values = [12:5,7:30,2:30,-3:30]

[sngls-h1]
; Tuned on O4b injections
statistic-keywords = statistic_correction:-7.3 reference_ifos:H1
; Value accounts for statistic correction
minimum-stat = -12

[sngls-l1]
; Tuned on O4b injections
statistic-keywords = statistic_correction:-4.9 reference_ifos:H1
; Value accounts for statistic correction
minimum-stat = -9

[sngls-v1]
; Tuned on O4b injections
statistic-keywords = statistic_correction:-7.3 reference_ifos:H1
; Value accounts for statistic correction
minimum-stat = -15

[sngls_statmap&sngls_statmap_inj]
far-calculation-method = H1:trigger_fit L1:trigger_fit V1:trigger_fit
fit-function = H1:exponential L1:exponential V1:exponential
; Values account for statistic corrections
fit-threshold = H1:-8 L1:-4.9 V1:-11.3

[hdfinjfind]
optimal-snr-column = H1:optimal_snr_H1 L1:optimal_snr_L1 V1:optimal_snr_V1
