; Chunk-specific information for chunk 35 of O3

[workflow]
start-time = 1265132995
end-time = 1265747453

[results_page]
analysis-title = "PyCBC offline search"
analysis-subtitle = "O3 broad analysis chunk 35"

[workflow-segments-dq]
segments-dq-file = https://git.ligo.org/pycbc/offline-analysis/-/raw/v2.3.14.6/production/o4/broad/dq_files/H1L1V1-DQ_FLAG-1417283334-1200809.xml

